Consolidate dl streamer
intel-retail/automated-self-checkout pull request #196
Opened 2023-07-31 23:42 UTC by brian-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-08-01 15:49 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
> +PRE_PROCESS="" #""|pre-process-backend=vaapi-surface-sharing|pre-process-backend=vaapi-surface-sharing pre-process-config=VAAPI_FAST_SCALE_LOAD_FACTOR=1
please default to some suitable value, asking the end developer to input all of that thing is too much IMO

2023-08-01 15:50 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
> +        fi
would suggest not asking the end user to do this input IMO

2023-08-01 15:50 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
why this file is empty?

2023-08-01 15:51 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
> +PRE_PROCESS="" #""|pre-process-backend=vaapi-surface-sharing|pre-process-backend=vaapi-surface-sharing pre-process-config=VAAPI_FAST_SCALE_LOAD_FACTOR=1
ditto

2023-08-01 15:51 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
> +    --pre_process)
ditto

2023-08-01 18:02 UTC, vli11 requested changes
I think we need to have https://github.com/brian-intel/automated-self-checkout/pull/4 merge into consolidateDLStreamer branch before this PR merging

2023-08-02 16:09 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-cpu.env
> +AGGREGATE=gvametaaggregate name=aggregate !
the value of the env variable needs to be double quoted since there is space and equal sign in between.

2023-08-02 16:09 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-cpu.env
> +DETECTION_OPTIONS=gpu-throughput-streams=4 nireq=4 batch-size=1
the value of the env variable needs to be double quoted since there is space and equal sign in between.

2023-08-02 16:09 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-cpu.env
> +CLASSIFICATION_OPTIONS=reclassify-interval=1 $DETECTION_OPTIONS
same here

2023-08-02 16:10 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-gpu.env
> +PRE_PROCESS=pre-process-backend=vaapi-surface-sharing pre-process-config=VAAPI_FAST_SCALE_LOAD_FACTOR=1
the value of the env variable needs to be double quoted since there is space and equal sign in between.

2023-08-02 16:11 UTC, vli11 commented
the value of the env variable needs to be double quoted since there is space and equal sign in between, there are many places are like that need to be updated

2023-08-03 20:53 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-gpu.env
> +DECODE=! vaapidecodebin
we need double quote around decode value

2023-08-03 20:57 UTC, vli11 commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-gpu.env
> +DECODE=! vaapidecodebin
actually you don't need the "! " in the front, the gst script already includes that

2023-08-03 21:16 UTC, vli11 approved these changes

2023-08-03 21:51 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
> +echo "run pipeline"
could you add what kind of pipeline is running here? eg. `run yolov5s detection only pipeline`

2023-08-03 21:51 UTC, jim-wang-intel commented on configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
> +echo "run pipeline"
ditto: `run yolov5s with OCR, barcode and classification pipeline`

2023-08-03 22:18 UTC, jim-wang-intel approved these changes
LGTM

2023-08-03 22:25 UTC, merged