feat: Download public models like the efficientnet classification model
intel-retail/automated-self-checkout pull request #277
Opened 2023-09-25 17:00 UTC by ejlee3

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

add ability to download public models like efficientnet
## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

run the script `./download_models/downloadOVMSModels.sh`

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-09-25 17:08 UTC, jim-wang-intel commented on download_models/downloadOVMSModels.sh
> +        cd "$omzModelDir" || { echo "Error: could not cd to folder \"$omzModelDir\"." ; exit 1; }
i just realized that we should not do exit 1 in this function call and we should return 1 to do better error handling.

2023-09-25 18:11 UTC, jim-wang-intel requested changes
check the comment about the subshell status code error handling logic

2023-09-25 18:11 UTC, jim-wang-intel commented on download_models/downloadOVMSModels.sh
ok @ejlee3 ,
 I am seeing this is executing inside the sub-shell: so it doesn't matter it is exit 1 or return 1. the whole thing inside subshell will be done after that and it continues the logic flow.  

So i think we should add the logic to get status code after that subshell call and return 1 or 0 correspondingly based on the status code returned from the subshell so that the caller of this function can do the error handling correctly.

2023-09-25 19:37 UTC, antoniomtz approved these changes
LGTM. tested locally

2023-09-25 22:13 UTC, brian-intel approved these changes

2023-09-26 19:55 UTC, antoniomtz approved these changes

2023-09-26 21:16 UTC, jim-wang-intel approved these changes
LGTM

2023-09-26 21:37 UTC, merged