feat: update object detection model and docs
intel-retail/automated-self-checkout pull request #319
Opened 2023-10-24 18:31 UTC by vli11

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [x] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?
update object detection model and docs

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
1. start camera simulator
2. run PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-10-24 18:38 UTC, NeethuES-intel commented on docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
> +TensorFlow Serving gRPC API, KServe gRPC API, TensorFlow Serving REST API, KServe REST API and OVMS C API through OpenVINO model server (OVMS). For running object detection pipeline, it is based on K
```suggestion
TensorFlow Serving gRPC API, KServe gRPC API, TensorFlow Serving REST API, KServe REST API and OVMS C API through OpenVINO model server (OVMS). For running object detection pipeline, based on KServe gRPC API method, default model used is ssd_mobilenet_v1_coco. You can use different model to run object detection. Here are the steps:
```

2023-10-24 19:43 UTC, antoniomtz requested changes

2023-10-24 19:43 UTC, antoniomtz commented on docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
> +3. Start simulator camera if not started: `./camera-simulator/camera-simulator.sh`
```suggestion
3. Start simulator camera if not started: `make run-camera-simulator`
```

2023-10-25 00:54 UTC, jim-wang-intel commented on docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
>      Please leave `target_device` value as it is, as the value `{target_device}` will be recognized and filled out by script run.
```suggestion
    Please leave `target_device` value as it is, as the value `{target_device}` will be recognized and replaced by script run.
```

2023-10-25 00:54 UTC, jim-wang-intel commented on docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
> +        └── variables
why this `ssd_mobilenet_v1_coco_2018_01_28` is a sub-directory of ssd_mobilenet_v1_coco? and do we need this folder?

2023-10-25 20:15 UTC, jim-wang-intel commented on docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
> +4. To start object detection pipeline: `PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms`
```suggestion
4. To start object detection pipeline: `PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms`
5. To stop the running pipelines: `make clean-profile-launcher` to stop and clean up the client side containers, or `make clean-all` to stop and clean up everything.
```

2023-10-25 20:41 UTC, jim-wang-intel approved these changes
LGTM

2023-10-25 20:45 UTC, antoniomtz approved these changes
LGTM

2023-10-25 20:46 UTC, merged