feat: download ovms models to requested precision only
intel-retail/automated-self-checkout pull request #327
Opened 2023-10-25 20:29 UTC by vli11

Closes: #326

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?
download ovms models to requested precision only

## Issue this PR will close

close: #326 

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
1. delete previously downloaded models folder under configs/opencv-ovms/models/2022
2. cd download_models
3. ./downloadOVMSModels.sh

after step 3, you should observe models been downloaded and only the requested precision folder been created download each model folder

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-10-25 20:45 UTC, jim-wang-intel requested changes

2023-10-25 20:45 UTC, jim-wang-intel commented on download_models/downloadOVMSModels.sh
> +    precision=$(echo "$eachModelBasePath" | rev | cut -d '/' -f 1 | rev)
suggest using awk is simpler and more performant:
```suggestion
    eachModel=$(echo "$eachModelBasePath" | awk -F/ '{print $(NF-1)}')
    precision=$(echo "$eachModelBasePath" | awk -F/ '{print $NF}')
```

2023-10-25 20:58 UTC, jim-wang-intel approved these changes
LGTM

2023-10-26 18:14 UTC, ejlee3 approved these changes
LGTM

2023-10-26 18:42 UTC, NeethuES-intel approved these changes
Small comment on message echo. LGTM

2023-10-26 18:42 UTC, NeethuES-intel commented on download_models/downloadOVMSModels.sh
> +                echo "downloaded"
```suggestion
                echo "Model already downloaded"
```

2023-10-26 18:42 UTC, NeethuES-intel commented on download_models/downloadOVMSModels.sh
> +                        echo "downloaded"
```suggestion
                        echo "Model already downloaded"
```

2023-10-26 19:05 UTC, merged