Capi yolov5
intel-retail/automated-self-checkout pull request #337
Opened 2023-11-06 23:03 UTC by vli11

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [x] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-11-06 23:32 UTC, jim-wang-intel requested changes
there are lots of duplicated codes.. can we change to re-use some of them?

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/Dockerfile.capi_yolov5
This Dockerfile has 99% of duplicates with theDockerfile.ovms-capi-gst .    please use the Dockerfile.ovms-capi-gst as the one docker to build capi-related docker images with different ARGS to parameterize the capi- build.

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/Makefile
> +		-t $(OVMS_CPP_DOCKER_IMAGE)-capi-yolov5:$(OVMS_CPP_IMAGE_TAG)
use the Dockerfile.ovms-capi-gst with build-arg for yolov5 to build.

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +int _window_height = 1080;
should this come from env instead of hard-coded?

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +        // TODO: Not implemented
remove

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +        // TODO: Not implemented
remove

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +                            //     j);
remove

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +        // printf("x0, y0: [%f] [%f] x1, y1: [%f] [%f]", x0, y0, x1, y1);
remove

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +}
is this one used? the scaler_w and scaler_h seems backwards.  if not used please remove this function

2023-11-06 23:32 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/run_capi_yolov5.sh
almost 100% duplication of run_face_detection.sh..... can we change this to use the same script?

2023-11-08 16:01 UTC, jim-wang-intel reviewed
overall LGTM, but when i ran with different WINDOW_WIDTH and WINDOW_HEIGHT values, the display bounding box is not changed according to both values. so looks like the width and height are still hard-coded.

2023-11-08 19:13 UTC, jim-wang-intel commented on configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
> +        cv::Size(inputShape[1], inputShape[2]);
remove this function call, as we dont need cv::Size() here i think

2023-11-09 15:25 UTC, jim-wang-intel commented on docs_src/OVMS/capiYolov5PipelineRun.md
> +Here is the template config file location: `configs/opencv-ovms/models/2022/config_template.json`, edit the file and append the new model's configuration into the template, such as we've yolov5 model
```suggestion
Here is the template config file location:[ `configs/opencv-ovms/models/2022/config_template.json`](https://github.com/intel-retail/automated-self-checkout/blob/main/configs/opencv-ovms/models/2022/config_template.json), edit the file and append the new model's configuration into the template, such as we've yolov5 model as shown below:
```

2023-11-09 15:25 UTC, jim-wang-intel commented on docs_src/OVMS/capiYolov5PipelineRun.md
> +The details about Profile Launcher configuration can be found [here](./profileLauncherConfigs.md), details for yolov5 pipeline profile launcher configuration can be viewed in `configs/opencv-ovms/cmd
```suggestion
The details about Profile Launcher configuration can be found [here](./profileLauncherConfigs.md), details for yolov5 pipeline profile launcher configuration can be viewed in[ `configs/opencv-ovms/cmd_client/res/capi_yolov5/configuration.yaml`](https://github.com/intel-retail/automated-self-checkout/tree/main/configs/opencv-ovms/cmd_client/res/capi_yolov5/configuration.yaml)
```

2023-11-09 15:25 UTC, jim-wang-intel commented on docs_src/OVMS/capiYolov5PipelineRun.md
> +    The pipeline will automatically download the OpenVINO model files listed in `configs/opencv-ovms/models/2022/config_template.json`
```suggestion
    The pipeline will automatically download the OpenVINO model files listed in [`configs/opencv-ovms/models/2022/config_template.json`](https://github.com/intel-retail/automated-self-checkout/blob/main/configs/opencv-ovms/models/2022/config_template.json)
```

2023-11-09 21:39 UTC, brian-intel approved these changes

2023-11-10 00:39 UTC, jim-wang-intel approved these changes
LGTM

2023-11-10 01:00 UTC, merged