fix: Default parameters and update documents
intel-retail/automated-self-checkout pull request #561
Opened 2024-04-30 21:41 UTC by brian-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

Default parameters and update documents

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2024-04-30 22:50 UTC, jim-wang-intel requested changes
this change using env-file breaks the command line override unless you change the envfile

2024-05-01 23:06 UTC, jim-wang-intel approved these changes
LGTM

2024-05-02 19:26 UTC, antoniomtz commented on docs_src/performance.md
> +make PIPELINE_COUNT=2 benchmark
do we need a section to explain how to specify a different pipeline other than the default?
or do we have that section already?

2024-05-02 20:09 UTC, antoniomtz approved these changes
LGTM

2024-05-02 20:45 UTC, merged