feat: Kubernetes support to Automated Self Checkout
intel-retail/automated-self-checkout pull request #581
Opened 2024-06-13 20:10 UTC by brian-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2024-06-13 20:28 UTC, antoniomtz requested changes

2024-06-13 20:28 UTC, antoniomtz commented on helm/docker-compose.yml
> +# Copyright (C) 2023 Intel Corporation.
```suggestion
# Copyright (C) 2024 Intel Corporation.
```

2024-06-13 20:28 UTC, antoniomtz commented on helm/Makefile
> +# Copyright © 2023 Intel Corporation. All rights reserved.
```suggestion
# Copyright © 2024 Intel Corporation. All rights reserved.
```

2024-06-13 20:28 UTC, antoniomtz commented on helm/Dockerfile.cam-sim
> +# Copyright (C) 2023 Intel Corporation.
```suggestion
# Copyright (C) 2024 Intel Corporation.
```

2024-06-13 20:28 UTC, antoniomtz commented on helm/Dockerfile
> +# Copyright (C) 2023 Intel Corporation.
```suggestion
# Copyright (C) 2024 Intel Corporation.
```

2024-06-13 20:28 UTC, antoniomtz commented on helm/kubernetes.md
> +helm repo index --url https://github.com/brian-intel/retail-use-cases .
do we want to update the github URL to the intel account?

2024-06-13 20:28 UTC, antoniomtz commented on helm/kubernetes.md
> +helm repo add dls https://brian-intel.github.io/retail-use-cases/
same for this one

2024-06-13 21:43 UTC, antoniomtz approved these changes

2024-06-14 00:43 UTC, antoniomtz approved these changes

2024-06-14 01:54 UTC, NeethuES-intel approved these changes
Minor change.

2024-06-14 01:54 UTC, NeethuES-intel commented on helm/kubernetes.md
> +You can restarting the cluster by running:
```suggestion
You can restart the cluster by running:
```

2024-06-14 18:31 UTC, merged