Feat: v3.1.0 merge to main
intel-retail/automated-self-checkout pull request #621
Opened 2024-09-27 00:08 UTC by brian-intel

## PR Checklist

- [ ] Added label to the Pull Request for easier discoverability and search
- [ ] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
- [ ] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

Merge v3.1.0 changes to main

## Issue this PR will close

close: #**issue_number**

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2024-09-30 21:47 UTC, antoniomtz requested changes

2024-09-30 21:47 UTC, antoniomtz commented on src/pipeline-server/docker-compose.pipeline-server.yml
> +      no_proxy: ${no_proxy}
I found an issue when setting proxies like this. The correct way is:

```suggestion
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
```

2024-09-30 21:47 UTC, antoniomtz commented on src/pipeline-server/Dockerfile.pipeline-server
> +FROM intel/edge_video_analytics_microservice:2.0.0
I didn't find this public image on dockerhub yet. How are we supposed to download it ? https://hub.docker.com/r/intel/edge_video_analytics_microservice/tags

2024-09-30 21:47 UTC, antoniomtz commented on src/pipeline-server/docker-compose.pipeline-server.yml
> +      no_proxy: ${no_proxy}
```suggestion
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
```

2024-09-30 21:47 UTC, antoniomtz commented on src/pipeline-server/docker-compose.pipeline-server.yml
> +      no_proxy: ${no_proxy}
```suggestion
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
```

2024-09-30 21:47 UTC, antoniomtz commented on src/pipeline-server/docker-compose.pipeline-server.yml
> +      no_proxy: ${no_proxy}
```suggestion
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
```

2024-10-07 21:48 UTC, NeethuES-intel approved these changes

2024-10-07 22:06 UTC, jim-wang-intel approved these changes

2024-10-08 17:26 UTC, antoniomtz approved these changes

2024-10-08 21:09 UTC, merged