fix: fixed docker-run.sh with wrong message when no --workload option
intel-retail/automated-self-checkout pull request #87
Opened 2023-06-12 21:43 UTC by vli11

Closes: #75

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [ ] Updated Documentation as relevant to the changes
- [x] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?
set WORKLOAD_SCRIPT default to docker-run-dlstream.sh so it will correct the message.

## Issue this PR will close

close: #75 

## Anything the reviewer should know when reviewing this PR?

## Test Instructions if applicable
1. go to xeon or arc supported machine using meshcentral.com
2. on automated-self-checkout directory, call command `./docker-run.sh --platform core --inputsrc rstp://127.0.0.1:8554/camera_0`
3. when not providing --workload, it should default to dlstreamer pipeline run.

## If the there are associated PRs in other repositories, please link them here (i.e. intel-retail/automated-self-checkout )

2023-06-12 23:22 UTC, jim-wang-intel requested changes

2023-06-12 23:22 UTC, jim-wang-intel commented on docker-run.sh
> +WORKLOAD_SCRIPT="docker-run-dlstreamer.sh"
please add a comment that if --workload is not provided this env is the default value will be used.

2023-06-13 16:25 UTC, jim-wang-intel requested changes

2023-06-13 16:25 UTC, jim-wang-intel commented on docker-run.sh
> +# Default WORKLOAD_SCRIPT to dlstreamer workload if not provided
what i meant is the comment of the relationship of this env value with --workload... as it is not very obvious this env will be overridden by that option below..kind of code maintainability.

2023-06-13 17:10 UTC, jim-wang-intel approved these changes
LGTM

2023-06-13 17:14 UTC, brian-intel approved these changes

2023-06-13 17:35 UTC, marcpfuller approved these changes

2023-06-13 18:11 UTC, merged